### ISSUE TITLE
发热特别严重，有没有优化方案？

### ISSUE THREAD

**Issue by WLZJ** [Guikunzhi/BeautifyFaceDemo#4]
首先，非常感谢您提供的美颜滤镜！
我在手机直播推流时，使用了它，但是，发现iPhone6s一下的手机，长时间（半个小时以上）使用，会发热严重，并且造成FPS极低（低于10）！您是否遇见过这种问题?有什么优化方案吗？

**Comment by Guikunzhi** [comment]
可以去掉边缘检测

发自 网易邮箱大师
在2016年08月29日 10:24，WLZJ 写道:

首先，非常感谢您提供的美颜滤镜！
我在手机直播推流时，使用了它，但是，发现iPhone6s一下的手机，长时间（半个小时以上）使用，会发热严重，并且造成FPS极低（低于10）！您是否遇见过这种问题?有什么优化方案吗？
